spring.application.name=api

# Configuracao do SQL Server (producao)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=apidb;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=@ITB123456
 
# Dialeto para SQL Server
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
 
# Em producao utilize "validate" para nao alterar o schema acidentalmente
# ou "update" para permitir a adicao de novas colunas sem recriar as tabelas
spring.jpa.hibernate.ddl-auto=update
 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
